apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: losbu1nmr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: losbu1nmr-python 
  name: losbu1nmr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: losbu1nmr-python 
